swagger: '2.0'
info:
  version: <auto>
  title: Bank File
  description: API for bank file
produces:
  - application/json
  - application/xml
host: <auto>
paths:
  '/outbound':
    get:
      summary: Get outbound bank files
      description: This route is used by the micro service that reads the inbound files. With applying on of the id filters it gets to know which transaction to update
      tags:
      - all
      - outbound
      parameters:
      - name: endToEndId
        in: query
        type: string
      responses:
        '200':
          description: A list of outbound bank files